### ISSUE TITLE
Developer friendly merging of defaults

### ISSUE THREAD

**Issue by sstok** [rollerworks/SkeletonDancer#5]
The following configuration doesn't work as expected.

``` yaml
defaults:
    name: '@"Park-Manager " ~ get_config("current_dir_name")'
    package_name: '@"park-mananger/" ~ humanize(get_config("current_dir_name"))'
    namespace: '@"ParkManager\\'
    php_min: '7.0'
    src_dir: src
    license: 'MPL-2.0'
    license_secondary_incompatibility: false
    sf_bundle_config_format: xml

profiles:
    park-manager-module-base:
        description: Base template for Park-Manager module related profiles.
        defaults:
            module_name: '@get_config("current_dir_name")'
            name: '@"Park-Manager " ~ module_name ~ " Module"'
            package_name: '@"park-mananger/" ~ humanize(get_config("current_dir_name")) ~ "-module"'
            namespace: '@"ParkManager\\Module\\" ~ get_config("current_dir_name")'
            doc_format: 'markdown' # Note that a Module's documentation is limited technical details
            composer_type: 'park-manager-module'
            sf_bundle_name: '@"ParkManager" ~ module_name ~ "Bundle"'
```

Because `name` is already defined in the defaults overwriting it will place it at a higher position then `module_name`, instead of using of using array_merge() there needs to be something better, that respects the position of the current defaults (the currently processed profile).
